//! # clipmesh-protocol
//!
//! The wire contract every ClipMesh node speaks: protobuf messages, the
//! length-delimited framing on top of TCP, and the validated clipboard payload
//! model.
//!
//! This crate is deliberately platform independent and dependency light. It
//! knows nothing about sockets, TLS, Tauri, Android or the operating system
//! clipboard - it only knows how to turn clipboard content into bytes and back
//! again, safely.
//!
//! ```no_run
//! use clipmesh_protocol::{DeviceId, Envelope, TextPayload};
//!
//! let payload = TextPayload::new_local("copied on device A", DeviceId::new());
//! let envelope = Envelope::text(payload.to_proto());
//! let frame = clipmesh_protocol::frame::encode(&envelope).unwrap();
//! assert_eq!(&frame[..4], &(frame.len() as u32 - 4).to_be_bytes());
//! ```

#![warn(missing_docs)]

pub mod clipboard;
pub mod device;
pub mod error;
pub mod frame;
pub mod message;

/// Generated protobuf types for `clipmesh.v1`.
///
/// Regenerated by `build.rs` on every change to `schema/clipmesh.proto`.
#[allow(missing_docs)]
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/clipmesh.v1.rs"));
}

pub use clipboard::{
    sha256_of, ClipboardContent, ClipboardItem, ClipboardKind, ImageMeta, ImagePayload,
    TextPayload, IMAGE_CHUNK_BYTES, IMAGE_MIME_PNG, MAX_IMAGE_BYTES, MAX_TEXT_BYTES,
};
pub use device::{DeviceId, DeviceInfo, Platform};
pub use error::{ProtocolError, Result};
pub use frame::{read_envelope, read_frame, write_envelope, MAX_FRAME_BYTES};
pub use message::{
    Ack, ClipboardImage, ClipboardText, Envelope, ErrorCode, ErrorMessage, Hello, HelloAck,
    ImageChunk, MessageKind, PairAccept, PairRequest, Payload, Ping, Pong, PROTOCOL_VERSION,
};

/// Current wall clock time in unix milliseconds.
///
/// Timestamps in the protocol are informational: they order history entries but
/// are never trusted for security decisions, because clocks drift and peers can
/// lie about them.
#[must_use]
pub fn now_millis() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};

    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |elapsed| elapsed.as_millis() as i64)
}
