# ClipMesh Android plugin - R8 rules its consumers must apply.
#
# A *consumer* rules file rather than a rule block in the app module's
# `gen/android/app/proguard-rules.pro`: the classes that must survive are this
# module's, `gen/android` is regenerated by `tauri android init`, and AGP folds
# this file into every minified consumer of `:bridge` automatically (see
# `consumerProguardFiles` in build.gradle.kts). The app's own R8 configuration
# shows the mechanism already working for the other two Tauri modules:
# `configuration.txt` contains sections "Local project :::tauri-android" and
# "Local project :::tauri-plugin-opener", extracted from their
# `build/intermediates/consumer_proguard_dir/`.

# ---------------------------------------------------------------------------
# Jackson command arguments
# ---------------------------------------------------------------------------
#
# `app.tauri.plugin.Invoke.parseArgs(Class)` deserialises a command's payload
# with Jackson *by reflection* over the class it is handed:
#
#     invoke.parseArgs(SetTextArgs::class.java)        # ClipMeshPlugin.setText
#     -> jsonMapper.readValue(argsJson, cls)
#
# R8 cannot follow that, so in the release build it renamed the argument classes
# and stripped their no-arg constructors and setters. Measured, from a real
# release build's `build/outputs/mapping/arm64Release/mapping.txt`:
#
#     app.cm.clipmesh.bridge.SetTextArgs   -> d20
#     app.cm.clipmesh.bridge.SetImageArgs  -> c20
#     app.cm.clipmesh.bridge.ShowReceivedArgs -> y20
#
# with `usage.txt` listing the removed members - `public void <init>()`,
# `setText(String)`, `setPng(String)`, `setTitle(String)`, ... The user-visible
# result was every command that takes arguments failing at the Jackson call:
#
#     Cannot construct instance of `d20` (no Creators, like default constructor,
#     exist): abstract types either need to be mapped to concrete types, have
#     custom deserializer, or contain additional type information
#
# Keeping the class NAME matters as much as keeping the members: Jackson derives
# a property's JSON key from the *name* of its setter or field (`setText` ->
# "text"), so a renamed setter would silently stop matching the payload that
# `apps/android/src-tauri/src/plugin.rs` serialises.
#
# `{ *; }` rather than a hand-written member list: adding a `var` to one of these
# classes adds a payload field, and that must not need a second edit here to keep
# working. The cost is three tiny classes R8 no longer shrinks.
#
# A new `@Command` that takes arguments means adding its argument class below.
#
# `-keepattributes` is deliberately NOT repeated here. AGP's default
# configuration (`proguard-android-optimize.txt`, section 1 of the same
# configuration.txt) already keeps `RuntimeVisibleAnnotations` and `Signature`,
# which is all Jackson's introspection needs, and these classes carry no Jackson
# annotations of their own - `@JsonProperty` and friends would only be needed if
# a property name ever stopped matching its JSON key by convention.
-keep class app.cm.clipmesh.bridge.SetTextArgs { *; }

-keep class app.cm.clipmesh.bridge.SetImageArgs { *; }

-keep class app.cm.clipmesh.bridge.ShowReceivedArgs { *; }

# ---------------------------------------------------------------------------
# The other reflective paths in this module, and why nothing is added for them
# ---------------------------------------------------------------------------
#
# `HostActivity.mainActivityClass` loads the application's activity with
# `Class.forName("${context.packageName}.MainActivity")`, which R8 cannot see
# either. It needs no rule: the class is the manifest's launcher activity, so AGP
# keeps it, by name, through the generated `aapt_rules.txt`
# (`-keep class app.cm.clipmesh.MainActivity { <init>(); }`) - confirmed against
# a release build's mapping.txt, where it is one of the few app classes with no
# rename target. The plugin's own manifest components (`BroadcastActivity`,
# `ClipMeshService`, `BootReceiver`, `ClipboardActionReceiver`) are kept the same
# way, and the `@Command` / `@PermissionCallback` methods - the other half of
# Tauri's reflective entry points, since `PluginManager` finds them by annotation -
# by `:tauri-android`'s own consumer rules, which the app's R8 configuration
# carries as a "Local project :::tauri-android" section, with every one of them
# listed in `seeds.txt`. The argument classes above were the only gap.
